# Generated by Django 5.2.5 on 2025-10-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(max_length=10),
        ),
    ]
